version: '3'

services:
  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_USERNAME: hoangdat12
      RABBITMQ_PASSWORD: hoangdat12
    networks:
      - broker_net
    ports:
      - 15672:15672
      - 5672:5672
    restart: always # always restart the container if it stops
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  postgres:
    container_name: postgres-container
    image: postgres:14.0
    environment:
      POSTGRES_DB: product_command_db
      POSTGRES_USER: hoangdat12
      POSTGRES_PASSWORD: hoangdat12
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready -U postgres_user']
    #   interval: 10s # Time interval between health checks
    #   timeout: 5s # Maximum time for each health check
    #   retries: 5 # Quantity retry for each health check
    networks:
      - db_net
    ports:
      - 5432:5432
    restart: unless-stopped
    # user: '1001:0'
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  db_net:
    name: db_net
  broker_net:
    name: broker_net

volumes:
  postgres_data:
